#cloud-config
chpasswd:
  list: |
    ${gh_username}:${password}
  expire: false
users:
  - default
  - name: shukawam
    lock_passwd: false
    groups: sudo, users, admin
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_import_id:
      - gh:${gh_username}
system_info:
  default_user:
    name: default-user
    lock_passwd: false
    sudo: ALL=(ALL) NOPASSWD:ALL
ssh_pwauth: no
random_seed:
  file: /dev/urandom
  command: ["pollinate", "-r", "-s", "https://entropy.ubuntu.com"]
  command_required: true
package_upgrade: true
packages:
  - curl
  - ca-certificates
  - vim
  - git
  - unzip
  - gnupg
  - lsb-release
  - dstat
  - jq
runcmd:
  - install -m 0755 -d /etc/apt/keyrings
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
  - chmod a+r /etc/apt/keyrings/docker.asc
  - |
    echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
      $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
       tee /etc/apt/sources.list.d/docker.list > /dev/null
  - apt-get update
  # Install docker
  - apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin -y
  - groupadd docker
  - usermod -aG docker $USER
  - newgrp docker
  - curl -LO "https://dl.k8s.io/release/$(curl -LS https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
  - chmod +x ./kubectl
  - mv ./kubectl /usr/local/bin/kubectl
  # Install fn project
  - curl -LSs https://raw.githubusercontent.com/fnproject/cli/master/install | sh
  # Install OCI CLI (default settings)
  - wget -O /tmp/install.sh https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh
  - chmod 755 /tmp/install.sh
  - /tmp/install.sh --accept-all-defaults
  - rm -rf /tmp/install.sh
