#cloud-config
chpasswd:
  list: |
    ${gh_username}:${password}
  expire: false
users:
  - default
  - name: shukawam
    lock_passwd: false
    groups: sudo, users, admin
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD=ALL']
    ssh_import_id:
      - gh:${gh_username}
system_info:
  default_user:
    name: default-user
    lock_passwd: false
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
ssh_pwauth: no
random_seed:
  file: /dev/urandom
  command: ["pollinate", "-r", "-s", "https://entropy.ubuntu.com"]
  command_required: true
package_upgrade: true
packages:
  - vim
  - git
  - unzip
  - gnupg
  - lsb-release
  - dstat
runcmd:
  # Add Docker's official GPG key:
  - sudo apt-get update
  - sudo apt-get install ca-certificates curl
  - sudo install -m 0755 -d /etc/apt/keyrings
  - sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
  - sudo chmod a+r /etc/apt/keyrings/docker.asc
  # Add the repository to Apt sources:
  - echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
      $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
      sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  - sudo apt-get update
  # Install docker
  - sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  # Manage Docker as a non-root user
  - sudo groupadd docker
  - sudo usermod -aG docker $USER
  - newgrp docker
  # install kubectl
  - curl -LO "https://dl.k8s.io/release/$(curl -LS https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
  - chmod +x ./kubectl
  - sudo mv ./kubectl /usr/local/bin/kubectl
  # install fn project
  - curl -LSs https://raw.githubusercontent.com/fnproject/cli/master/install | sh
  # Install OCI CLI (default settings)
  - bash -c "$(curl -L https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh)" --accept-all-defaults
